### ISSUE TITLE
Browser Path For MacOS Chrome is Wrong

### ISSUE THREAD

**Issue by ebebbington** [caspervonb/deno-web#5]
not sure if it's just my mac, but for me, chrome is located at `/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome`, as opposed to what is in your `browser.ts`: `/Applications/Google\ Chrome.app/Contents/MacOS/Google`

![image](https://user-images.githubusercontent.com/47337480/94343408-e1ef5500-000f-11eb-82e9-3dc90257a512.png)

**Comment by caspervonb** [comment]
That's what it is? 😉 

>  /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome

https://github.com/caspervonb/deno-web/blob/08cede96e6df55b82d1e08a8d240ef2b80182e8d/browser.ts#L47

**Comment by ebebbington** [comment]
wait what... ok hold on lol

**Comment by ebebbington** [comment]
So it is 🤔 Not sure why how i thought it was...
